// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ThemePanel(disable bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- BEGIN theme-panel --><div class=\"app-theme-panel\" style=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues(templ.KV("display: none", disable))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `cmd/web/view/component/layout/theme_panel.templ`, Line: 5, Col: 73}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><div class=\"app-theme-panel-container\"><a href=\"javascript:;\" data-toggle=\"theme-panel-expand\" class=\"app-theme-toggle-btn\"><i class=\"bi bi-sliders\"></i></a><div class=\"app-theme-panel-content\"><div class=\"small fw-bold text-inverse mb-1\">Préférence</div><div class=\"card mb-3\"><!-- BEGIN card-body --><div class=\"card-body p-2\"><div class=\"row gx-2\"><div class=\"col-6\"><a href=\"javascript:;\" data-toggle=\"theme-mode-selector\" data-theme-mode=\"dark\" class=\"app-theme-mode-link active\"><div class=\"img\"><img src=\"/public/img/mode/dark.jpg\" class=\"object-fit-cover\" height=\"76\" width=\"76\" alt=\"Dark Mode\"></div><div class=\"text\">Sombre</div></a></div><div class=\"col-6\"><a href=\"javascript:;\" data-toggle=\"theme-mode-selector\" data-theme-mode=\"light\" class=\"app-theme-mode-link\"><div class=\"img\"><img src=\"/public/img/mode/light.jpg\" class=\"object-fit-cover\" height=\"76\" width=\"76\" alt=\"Light Mode\"></div><div class=\"text\">Claire</div></a></div></div></div><!-- END card-body --><!-- BEGIN card-arrow --><div class=\"card-arrow\"><div class=\"card-arrow-top-left\"></div><div class=\"card-arrow-top-right\"></div><div class=\"card-arrow-bottom-left\"></div><div class=\"card-arrow-bottom-right\"></div></div><!-- END card-arrow --></div></div></div></div><!-- END theme-panel -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
