// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "app/cmd/web/view/component"
import "app/cmd/web/viewmodel"
import "github.com/socle-lab/render"

func SignIn(td *render.TemplateData, i interface{}) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		vm := i.(*viewmodel.IndexViewModel)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- BEGIN #app --> <div id=\"app\" class=\"app app-full-height app-without-header\"><!-- BEGIN login --><div class=\"login\"><!-- BEGIN login-content --><div class=\"login-content\"><form action=\"/connexion/signin\" method=\"POST\" name=\"login_form\"><h1 class=\"text-center\">Sign In</h1><div class=\"text-inverse text-opacity-50 text-center mb-4\">For your protection, please verify your identity.</div><div class=\"mb-3\"><label class=\"form-label\">Email Address <span class=\"text-danger\">*</span></label> <input type=\"email\" name=\"email\" class=\"form-control form-control-lg bg-inverse bg-opacity-5\" value=\"\" placeholder=\"Enter your email\" required></div><div class=\"mb-3\"><div class=\"d-flex\"><label class=\"form-label\">Password <span class=\"text-danger\">*</span></label> <a href=\"#\" class=\"ms-auto text-inverse text-decoration-none text-opacity-50\">Forgot password?</a></div><input type=\"password\" name=\"password\" class=\"form-control form-control-lg bg-inverse bg-opacity-5\" value=\"\" placeholder=\"Enter your password\" required></div><div class=\"mb-3\"><div class=\"form-check\"><input class=\"form-check-input\" type=\"checkbox\" name=\"remember_me\" value=\"1\" id=\"customCheck1\"> <label class=\"form-check-label\" for=\"customCheck1\">Remember me</label></div></div><button type=\"submit\" class=\"btn btn-outline-theme btn-lg d-block w-100 fw-500 mb-3\">Sign In</button><div class=\"text-center text-inverse text-opacity-50\">Don't have an account yet? <a href=\"page_register.html\">Sign up</a>.</div></form></div><!-- END login-content --></div><!-- END login --></div><!-- END #app -->")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = component.BaseMinimal(vm.Title, td).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
