// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package component

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/socle-lab/render"

func BaseMinimal(title string, td *render.TemplateData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\" data-bs-theme=\"dark\"><head><meta charset=\"utf-8\"><title>PISCILL-POS | ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `cmd/web/view/component/layout_minimal.templ`, Line: 11, Col: 31}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><meta name=\"description\" content=\"\"><meta name=\"author\" content=\"\"><!-- PNG icon --><link rel=\"icon\" href=\"/public/favicon.ico\" type=\"image/x-icon\"><!-- ================== BEGIN core-css ================== --><link href=\"/public/css/vendor.min.css\" rel=\"stylesheet\"><link href=\"/public/css/app.min.css\" rel=\"stylesheet\"><link href=\"/public/css/custom.css\" rel=\"stylesheet\"><!-- ================== END core-css ================== --><link href=\"/public/plugins/blueimp-file-upload/css/jquery.fileupload.css\" rel=\"stylesheet\"><meta name=\"csrf-token\" content=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(td.CSRFToken)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `cmd/web/view/component/layout_minimal.templ`, Line: 24, Col: 49}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"><!-- ================== BEGIN page-css ================== --><link href=\"/public/plugins/jvectormap-next/jquery-jvectormap.css\" rel=\"stylesheet\"><!-- ================== END page-css ================== --><script src=\"/public/js/htmx.min.js\"></script><script defer src=\"/public/js/alpine.min.js\"></script></head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<!-- ================== BEGIN core-js ================== --><script src=\"/public/js/vendor.min.js\"></script><script src=\"/public/js/app.min.js\"></script><!-- ================== END core-js ================== --><!-- ================== BEGIN page-js ================== --><script src=\"https://code.iconify.design/iconify-icon/2.1.0/iconify-icon.min.js\"></script><!-- ================== END page-js ================== --><script>\n        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle=\"tooltip\"]');\n        const tooltipList = [...tooltipTriggerList].map(el => new bootstrap.Tooltip(el));\n    </script><script src=\"/public/plugins/blueimp-file-upload/js/vendor/jquery.ui.widget.js\"></script><script src=\"/public/plugins/blueimp-tmpl/js/tmpl.min.js\"></script><script src=\"/public/plugins/blueimp-load-image/js/load-image.all.min.js\"></script><script src=\"/public/plugins/blueimp-canvas-to-blob/js/canvas-to-blob.min.js\"></script><script src=\"/public/plugins/blueimp-gallery/js/jquery.blueimp-gallery.min.js\"></script><script src=\"/public/plugins/blueimp-file-upload/js/jquery.iframe-transport.js\"></script><script src=\"/public/plugins/blueimp-file-upload/js/jquery.fileupload.js\"></script><script src=\"/public/plugins/blueimp-file-upload/js/jquery.fileupload-process.js\"></script><script src=\"/public/plugins/blueimp-file-upload/js/jquery.fileupload-image.js\"></script><script src=\"/public/plugins/blueimp-file-upload/js/jquery.fileupload-audio.js\"></script><script src=\"/public/plugins/blueimp-file-upload/js/jquery.fileupload-video.js\"></script><script src=\"/public/plugins/blueimp-file-upload/js/jquery.fileupload-validate.js\"></script><script src=\"/public/plugins/blueimp-file-upload/js/jquery.fileupload-ui.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
